{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- end -}}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end -}}
